# Use Nginx as base image
FROM nginx:alpine

# Remove Nginx's default configuration
RUN rm /etc/nginx/conf.d/default.conf

# Add our own configuration
COPY nginx.conf /etc/nginx/conf.d

# Copy the built static files into Nginx's default folder
COPY ./dist /usr/share/nginx/html

# Expose port 80 on the container to receive requests
EXPOSE 80

# Start the Nginx service
CMD ["nginx", "-g", "daemon off;"]
