# 使用Nginx作为基础镜像
FROM nginx:alpine

# 删除nginx 默认配置
RUN rm /etc/nginx/conf.d/default.conf

# 添加我们自己的配置
COPY nginx.conf /etc/nginx/conf.d

# 将构建的静态文件复制到 Nginx 的默认文件夹
COPY ./dist /usr/share/nginx/html

# 容器暴露80端口，使其可以接收请求
EXPOSE 80

# 启动Nginx服务
CMD ["nginx", "-g", "daemon off;"]