version: '3'
services:
  frontend:
    image: frontend
    ports:
      - "8081:80"
    networks:
      - frontend_net
    deploy:
      replicas: 3
networks:
  frontend_net:
    driver: overlay
