- name: Deploy Docker Swarm
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Initialize Docker Swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ ansible_default_ipv4.address }}"
      when: "'manager' in group_names"

    - name: Get Swarm Manager join-token
      command: docker swarm join-token -q manager
      register: manager_token
      run_once: true
      delegate_to: "{{ groups['manager'][0] }}"

    - name: Join nodes to Docker Swarm
      docker_swarm:
        state: join
        advertise_addr: "{{ ansible_default_ipv4.address }}"
        join_token: "{{ manager_token.stdout }}"
        remote_addrs: [ "{{ groups['manager'][0] }}:2377" ]
      when: "'worker' in group_names"

    - name: Install Docker Compose library
      ansible.builtin.pip:
        name: docker-compose
        state: present
      run_once: true
      delegate_to: "{{ groups['manager'][0] }}"


