- name: deploy docker
  hosts: localhost
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Start docker service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: docker

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{docker_username}}"
        password: "{{docker_password}}"

    - name: Create docker network
      community.docker.docker_network:
        name: network_1
        state: present

    - name: Build Mastodon Docker image
      community.docker.docker_image:
        name: mastodon
        build:
          path: /home/ubuntu/90024_A2
          dockerfile: Dockerfile
          pull: yes
        source: build

    - name: Deploy Mastodon
      docker_container:
        image: "mastodon"
        state: started
        recreate: yes
        published_ports:
          - "8081:80"
        networks:
          - name: network_1
