- name: deploy docker
  hosts: localhost
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Start docker service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: docker

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{docker_username}}"
        password: "{{docker_password}}"

    - name: Create docker network
      community.docker.docker_network:
        name: network_1
        state: present


    - name: Build backend Docker image
      community.docker.docker_image:
          name: backend22
          build:
            path: /home/ubuntu/90024_A2
            dockerfile: Dockerfile
            pull: yes
          source: build


    - name: Deploy backend
      docker_container:
        image: "backend22"
        state: started
        recreate: yes
        published_ports:
          - "8080:8080"
        networks:
          - name: network_1

