# Use official Python 3.9 image as base image
FROM python:3.9-slim-buster

# Set the working directory
WORKDIR /app

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    gcc g++ --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Install the project's required dependencies
RUN pip install --no-cache-dir mastodon.py couchdb python-dotenv nltk transformers torch langdetect beautifulsoup4 emoji

# Download the NLTK stopwords resource
RUN python -m nltk.downloader stopwords punkt

# Add the required Python scripts to the container
COPY Mastodon_Crawl_1.py Mastodon_Crawl_2.py Mastodon_Crawl_3.py start.sh /app/

# Add execution permissions to the shell script
RUN chmod +x /app/start.sh

# Run the crawler command
CMD ["/app/start.sh"]


