- name: deploy docker
  hosts: worker
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Start docker service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: docker

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{docker_username}}"
        password: "{{docker_password}}"

    - name: Create docker network
      community.docker.docker_network:
        name: network_1
        state: present

    - name: Stop CouchDB Docker container
      docker_container:
        name: couchdb
        state: absent

    # Create new docker container for CouchDB and start container
    - name: Create and start CouchDB Docker container
      docker_container:
        name: couchdb666
        image: "couchdb:latest"
        state: started
        recreate: true
        ports:
          - "5984:5984"
          - "4369:4369"
          - "9100-9200:9100-9200"
        pull: yes
        env:
          COUCHDB_USER: "{{ db_user }}"
          COUCHDB_PASSWORD: "{{ db_password }}"
          COUCHDB_SECRET: "{{ cookie }}"
          ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""


